services:
  hugo:
    image: ghcr.io/gohugoio/hugo:v0.154.4
    command: >
      server
      --bind 0.0.0.0
      --disableFastRender
    ports:
      - "1313:1313"
    volumes:
      - ../../site:/project
    working_dir: /project
